version: 0.2

phases:
  install:
    commands:
      - npm install
      - npm install -g serverless@3.38
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - serverless deploy -v

artifacts:
  files:
    - "**/*"
  discard-paths: yes
