service: codebuild-to-discord

frameworkVersion: "3"

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/1243171226629963889/DlOVIgm0uYGzQYFQCIouhPd1AwZuC6P0ADAM_5CR56PbuwyQ8pvThub1yF7Itv9J6TYP"

functions:
  notifyDiscord:
    handler: src/handler.lambdaHandler
    events:
      - sns: ${self:custom.snsTopicArn_fe}
      - sns: ${self:custom.snsTopicArn_be}
         

custom:
  snsTopicArn_fe: arn:aws:sns:us-east-1:908991390875:CodeStarNotifications-monetizely-core-fe-build-af6f1229e22e32a677b8b5a306d20c700450414e
  snsTopicArn_be: arn:aws:sns:us-east-1:908991390875:CodeStarNotifications-monetizely-core-be-build-0daa5a2132afcc333faf4613082c0037a5f21d3b

