service: codebuild-to-discord

frameworkVersion: "3"

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  environment:
    DISCORD_WEBHOOK_URL: ${ssm:/discord/webhook/url}

functions:
  notifyDiscord:
    handler: src/handler.lambdaHandler
    events:
      - sns: ${self:custom.snsTopicArn}

custom:
  snsTopicArn: arn:aws:sns:us-east-1:908991390875:CodeStarNotifications-monetizely-core-fe-build-af6f1229e22e32a677b8b5a306d20c700450414e
